namespace Heimdall.Server
{
    /// <summary>
    /// Describes the result of a Heimdall static site generation run.
    /// </summary>
    public sealed class HeimdallStaticSiteGenerationResult
    {
        internal HeimdallStaticSiteGenerationResult(
            string outputRootPath,
            IReadOnlyList<HeimdallStaticPageOutput> pages,
            IReadOnlyList<HeimdallStaticAssetOutput> assets,
            IReadOnlyList<HeimdallStaticSupplementalFileOutput> supplementalFiles,
            string? manifestFilePath)
        {
            OutputRootPath = outputRootPath;
            Pages = pages;
            Assets = assets;
            SupplementalFiles = supplementalFiles;
            ManifestFilePath = manifestFilePath;
        }

        /// <summary>
        /// Gets the absolute root directory that received generated files.
        /// </summary>
        public string OutputRootPath { get; }

        /// <summary>
        /// Gets the pages that were generated.
        /// </summary>
        public IReadOnlyList<HeimdallStaticPageOutput> Pages { get; }

        /// <summary>
        /// Gets the web root assets that were copied.
        /// </summary>
        public IReadOnlyList<HeimdallStaticAssetOutput> Assets { get; }

        /// <summary>
        /// Gets supplemental files generated by Heimdall, such as sitemap.xml and robots.txt.
        /// </summary>
        public IReadOnlyList<HeimdallStaticSupplementalFileOutput> SupplementalFiles { get; }

        /// <summary>
        /// Gets the generated manifest file path, when manifest writing is enabled.
        /// </summary>
        public string? ManifestFilePath { get; }
    }

    /// <summary>
    /// Describes a generated Heimdall static page.
    /// </summary>
    /// <param name="Route">The normalized route that was rendered.</param>
    /// <param name="FilePath">The absolute generated file path.</param>
    /// <param name="BytesWritten">The number of UTF-8 bytes written to disk.</param>
    public sealed record HeimdallStaticPageOutput(
        string Route,
        string FilePath,
        long BytesWritten);

    /// <summary>
    /// Describes a copied Heimdall static site asset.
    /// </summary>
    /// <param name="SourcePath">The absolute source file path.</param>
    /// <param name="FilePath">The absolute generated file path.</param>
    /// <param name="BytesWritten">The number of bytes written to disk.</param>
    public sealed record HeimdallStaticAssetOutput(
        string SourcePath,
        string FilePath,
        long BytesWritten);

    /// <summary>
    /// Describes a supplemental Heimdall static site file.
    /// </summary>
    /// <param name="Kind">The supplemental file kind.</param>
    /// <param name="FilePath">The absolute generated file path.</param>
    /// <param name="BytesWritten">The number of UTF-8 bytes written to disk.</param>
    public sealed record HeimdallStaticSupplementalFileOutput(
        string Kind,
        string FilePath,
        long BytesWritten);
}
