<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>HeimdallFramework.Server</PackageId>
		<Version>3.0.9</Version>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<Authors>Bradley Ables</Authors>
		<Description>Heimdall server-side middleware, endpoints, and action pipeline for HTML-first server invocations.</Description>
		<PackageTags>heimdall framework;html;SSR;MVC;rpc;aspnetcore;middleware;sse</PackageTags>
		<RepositoryUrl>https://github.com/bradleyables22/Heimdall</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<PackageIcon>favicon.png</PackageIcon>

		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>


	<ItemGroup>
		<None Include="Favicon.png" Pack="true" PackagePath="favicon.png" />
		<None Include="..\LICENSE" Pack="true" PackagePath="\" Link="LICENSE" />
		<None Include="readme.md" Pack="true" PackagePath="\" />
		<None Include="CHANGELOG.md" Pack="true" PackagePath="\" />
		<None Include="buildTransitive\HeimdallFramework.Server.targets" Pack="true" PackagePath="buildTransitive\HeimdallFramework.Server.targets" />
	</ItemGroup>

</Project>
